In [ ]:
ndarray.ndim
数组轴的个数，在python的世界中，轴的个数被称作秩
ndarray.shape
数组的维度。这是一个指示数组在每个维度上大小的整数元组。例如一个n排m列的矩阵，它的shape属性将是(2,3),这个元组的长度显然是秩，即维度或者ndim属性

In [1]:
import numpy as np

In [5]:
np.ones((2, 3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#NumPy中的乘法运算符*指示按元素计算，矩阵乘法可以使用dot函数或创建矩阵对象实现

In [34]:
a = np.array([[1, 4, 5, 6, 12, 34, 56], [2, 3, 5, 3, 23, 67, 31]])
b = np.array([[1, 2], [0, 5]])
a * b
np.dot(a, b)

array([[ 1, 22],
       [ 2, 19]])

In [26]:
#dir(np)

In [29]:
np.power(a, b)

array([[  1,   4],
       [  1, 243]], dtype=int32)

In [43]:
np.std(a)

1.118033988749895

In [54]:
a = np.array([[1, 4, 5, 5, 12, 34, 56], [2, 4, 5, 3, 23, 67, 31]])
a

array([[ 1,  4,  5,  5, 12, 34, 56],
       [ 2,  4,  5,  3, 23, 67, 31]])

In [58]:
np.unique(a[:,0])

array([1, 2])

In [60]:
np.intersect1d(a, b)

array([1, 2, 5])

In [62]:
np.in1d(a, b)

array([ True, False,  True,  True, False, False, False,  True, False,
        True, False, False, False, False])

In [69]:
np.linalg.svd(b)

(array([[ 0.38268343, -0.92387953],
        [ 0.92387953,  0.38268343]]),
 array([5.39834564, 0.92620968]),
 array([[ 0.07088902,  0.99748421],
        [-0.99748421,  0.07088902]]))

In [70]:
a

array([[ 1,  4,  5,  5, 12, 34, 56],
       [ 2,  4,  5,  3, 23, 67, 31]])

In [75]:
a.take([13])

array([31])

In [77]:
np.arange(10).reshape((2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [81]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [82]:
b = np.array([[1, 2],[2, 3],[3, 4],[4, 5]])
b

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5]])

In [84]:
a.dot(b)

array([30, 40])

In [85]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [88]:
c = np.array([2, 3, 4, 5])
c

array([2, 3, 4, 5])

In [91]:
np.dot(a, c)

40

In [93]:
from pandas import Series, DataFrame
import pandas as pd

In [98]:
s1 = Series([1, 2, 3, 4], index = ['a','b', 'c', 'd'])
s2 = Series([2, 3, 4, 5])
print(s1)
print(s2)

a    1
b    2
c    3
d    4
dtype: int64
0    2
1    3
2    4
3    5
dtype: int64


In [99]:
s1 * s2

a   NaN
b   NaN
c   NaN
d   NaN
0   NaN
1   NaN
2   NaN
3   NaN
dtype: float64

0     2
1     6
2    12
3    20
dtype: int64